# Research

Read chapters 1-5 to learn more [about the research process generally](https://bookdown.org/pkaldunn/Book/Intro.html).

## Selecting a group to study

Now that you have a sense of why phylogenies are so important
you can start to think about a group whose evolutionary history you might like to investigate.
Our understanding of how species are related is constantly changing.
That means that you can play a role you can play in determining how evolution happened.

You can pick any group to study or ask your instructor for suggestions.
Once you pick a group you'll need to investigate it a bit more to determine
whether you can narrow your research to address particularly interesting research questions,
and then determine whether there are data to help you answer those questions.
You might consider picking a group that is studied by URI faculty.

If you still need ideas [click here](research-ideas.html).

## Learning about your group

You will need to do some background research to learn about 
the group you propose to study, and to provide motivation of your work.
Check out the URI Library's [Basics of College Level Research](https://www.youtube.com/watch?v=v5AWzB_CKIs&t=241s).

### Finding research articles

To get started find out something about your group.
You can start with Google, although you should rapidly move on to searching the primary literature.
Learn about [scholarly and popular sources](https://www.youtube.com/watch?v=IZzX3VcyYLk&t=147s) to understand why you need to go beyond popular or secondary literature.
Also check out the URI Library's discussion on [why not just search Google](https://www.youtube.com/watch?v=gpOjKqUkMNY&t=96s).
For general suggestions on finding literature on your topic see the URI Library's guide to [finding journal articles](https://www.youtube.com/watch?v=xbL3OiKZbqM&t=174s).

The URI Library offers a variety of databases for research, but Google Scholar can be a good way to find literature on your topic.

How to use Google Scholar:

* [https://www.youtube.com/watch?v=B7bUS9TYvRU](https://www.youtube.com/watch?v=B7bUS9TYvRU)
* [https://www.youtube.com/watch?v=6vSE-_iq7NE](https://www.youtube.com/watch?v=6vSE-_iq7NE)
* [URI's guide to Google Scholar](https://uri.libguides.com/google/gschol)

If you are struggling to find papers that seem relevant to your research topic try the URI Library's guide to [developing an effective search strategy](https://www.youtube.com/watch?v=vpw8aysfdng).

When you find an article you want, you can access it as a member of the URI community.
However, if you are off campus the journal may not recognize you.
In Google Scholar click the menu bar in the upper left and choose settings.
Search for the University of Rhode Island and select URI library.
Google Scholar will now have Search @ URI Libraries on the right if there's an article you want.

If you still have problems you may need to search for you article via the library website.

* Go to [https://web.uri.edu/library/](https://web.uri.edu/library/).
* Under Find Resources paste the name of an article of interest and Search.
* Find the online resource that allows you to have access and sign in with your URI login.
* If URI has access to the article you should be able to read it.
* You may need to repeat your search on the URI website for other articles depending on your connection.

### Reading research articles

Once you locate a paper to read you need to read it.
Check out these recommendations on how to read a paper efficiently and effectively: 

* [https://www.youtube.com/watch?v=Gv5ku0eoY6k](https://www.youtube.com/watch?v=Gv5ku0eoY6k)
* [https://www.youtube.com/watch?v=IeaD0ZaUJ3Y](https://www.youtube.com/watch?v=IeaD0ZaUJ3Y)

### Reading for your research

In class we will start to search for and read background material using the [Citation Tracking Activity](citation-tracker-exercise.html). 

After some background research you may have a preliminary idea of which group to study, and hopefully you have a good reason for this group.
Keep in mind that you may be fascinated by a particular group of species, but you still have to convince others to be equally fascinated.
If you aren't sure, try explaining your project to a friend or roommate.
Also check out [past projects](research-ideas.html) for example research questions.

### More background information

Now that you have a group of species and a (possibly vague) question you can begin to write your ideas.
You won't have everything pinned down precisely, but write down what you have.
Let's research your group a bit more.
First, find out more about your group, particularly the number of species and its age,
by looking at Wikipedia and searching Google.
If you picked a group that has a lot of species (e.g. birds, mammals),
see if you can pick a smaller clade within your group of interest.
You can also find out more about the species in your group by searching
the [TimeTree](http://timetree.org/).

## Freewrite assignment

At this point you should have a lot of ideas in your head.
Now is the time to write them down.
When scientists plan their research project they typically do a lot of writing.
In this end this kind of writing turns into a formal research proposal,
but the process of shaping that proposal usually starts with lots of notes about
(1) what the researcher thinks the question is at the beginning, and
(2) what is known in the field from reading a lot of papers.

You are going to work through this process now to make a plan for your own research.
First, write 1-2 pages of what you think your question is, why it's interesting,
and what is known in the field.
If writing makes you think your question has already been answered, or needs more work before you
can answer it, write all that down.
You have two options here, first to truly freewrite your thoughts and see how they evolve and change,
and second to go back and change your question if you discover it needs refinement.
Either way, don't get bogged down in details or grammar - try to get your ideas and background onto the paper.
You should use this assignment to seek your plan and question yourself as to whether it will be successful.
Think about this piece of work like an artist's sketchbook that requires multiple tries to produce something that seems good.

We will use this writing for discussion in class where you will have a chance to get comments so that you can have the best research plan moving forward.
A successful freewrite will make you feel like you have a question and plan that will stand up to skeptical questioning by your peers.

## Annotated Bibliography assignment

Once you really know what you want to work on,
you should make sure you understand the background to your research.
That means reading the primary literature in more depth.
An annotated bibliography can help you organize your understanding of this material.

Develop an annotated bibliography of at least 5 sources.
Note that you may need to skim 10-20 papers before settling on 5 to read in depth.
See suggestions above for how to find and read papers.
Your annotated bibliography should include the full citation (and probably a link for later use) followed by a 1-2 paragraph summary and/or bullets of the important points (particularly results) in the article as they relate to your research.
The format is not critical.
Note that an annotated bibliography is not an abstract.
The annotated bibliography is for you to use later so take notes on what's important for your research.

Here are some examples and references:  

* [https://owl.purdue.edu/owl/general_writing/common_writing_assignments/annotated_bibliographies/annotated_bibliography_samples.html](https://owl.purdue.edu/owl/general_writing/common_writing_assignments/annotated_bibliographies/annotated_bibliography_samples.html)
* [https://guides.library.cornell.edu/annotatedbibliography](https://guides.library.cornell.edu/annotatedbibliography)

## Reflection assignment

Write a short reflection on your annotatated bibliography.

* Why did you select the papers you chose to read more in depth?
* Why did you feel that the remaining papers were less relevant?
* Do you feel that your research question is strong and well motivated? Explain why.
