# Getting the computer to run analyses

Rather than counting how much data we have by hand, let's get the computer
to do this tedious work for us.
To get started 

1. Log in to the [RStudio Server](https://celsrs.uri.edu/) on campus.
2. Enter your username (the first part of your email address) and password (URI student ID)
3. Make a new project to work on this research project
4. Use the Upload button (lower right) to upload the file of information you obtained from ENA
5. Click the Terminal tab and type

```
Rscript ../../shared/make_download_script.R [file] [target_data_size] [outfile]
```

Replace the items in brackets with:

1. your file from ENA
2. target data size should be in Mbp - get genome size, multiply by coverage, and round up significantly
3. a name you determine to save information to

Now click on the output files to fine out what species have enough data to work with.
If you are satisfied with the available data continue.
Otherwise you might need to try a different group.
