# Computational skills

The data you are working with is too large to analyze by hand.
For example, the human genome is 3.2 billion bases.
It would be hard to compare all that data to data from other species just using your eyes.
Instead we're going to need to learn some basic programming skills 
so we can tell the computer how to work with our data.

First, you'll have noticed that the computer we're using doesn't have the graphical interface
you usually use (like a PC or Mac).
That means you have to type in your commands - you can't point and click.
This actually has a hidden benefit because it's easy to write down what you did in
a line of text rather than having to try to explain where to click on each step.

Let's start by learning how to log in the our server and run commands without clicking.

## Log in to the server

Mac:

* open your Terminal (you may need to search for it)
* at the prompt type `ssh -l username bluewaves.uri.edu` , replacing `username` with the first part of your email address.
* you should be prompted to enter a password of your choice - note that the password does not show up when you type
* you should arrive at a prompt for bluewaves

PC:

* Download and install [git-bash](https://gitforwindows.org/). 
* open git-bash 
* at the prompt type `ssh -l username bluewaves.uri.edu` , replacing username with the first part of your email address.
* you should be prompted to enter a password of your choice - note that the password does not show up when you type
* you should arrive at a prompt for bluewaves

## Basic navigation

You are now logged in to bluewaves, which is a cluster of computers that can be used for research.
First, you'll need to learn to navigate around only by typing.
Computing clusters typically require you to type all the commands.

For example, to list all the files in your home folder (where you are when you log in) type `ls`.
There probably isn't anything in this folder right now.
This is just like opening a folder in a Finder window on a Mac or a folder on a PC,
except you had to type the command instead of simply double clicking.

Second (and to help you get used to typing instead of clicking), let's find out
where we are in the folder structure.
You should be in your home folder, which is inside another folder,
and so on and so forth.
Think of it as a highly organized filing cabinet, and you will need to move in between folders
to access files.
Type `pwd` to see the folder you are in.
You'll see your folder at the end, preceeded by a slash, preceeded by another folder, and so on.

Let's start by making a new folder to put your work in.
Use the `mkdir` command to make a new directory.
Unlike the prior commands you learned, but like most commands you'll use,
this command also takes an argument, which is another "word" that comes after this command.
When you make a directory you need to name it, so instead of just
`mkdir` you need `mkdir data` or  or some other folder name.

Now that you have a new folder open it up.
You change the directory using the `cd` command.
Again, this command takes an argument so you'll type `cd data`.

Type `pwd` again.
Notice what folder you are in.
To go back to the folder containing your current folder type `cd ..`, which will take you one level up in the folder hierarchy.
Type `pwd` again to see where you are now.

Adapted from  http://swcarpentry.github.io/shell-novice/

