# Sharing your results

Scientific results are typically shared via (1) the kind of research paper you have been reading as background for your work, and (2) presentations to an audience of peers. We will use both approaches in this class.

## Presentation

1. Slides on your study group. Don't forget to convince your uninformed audience that this is the most fascinating group in the world with lots to help up understand about evolution.
2. Slides on the information that isn't known about this group - i.e. the question you will answer. Make sure we're convinced that the question you answer will help us address all those cool questions you raised in 1.
3. Your methods - briefly. Describe the approach, not the steps you take on the computer. Talk about methods, not software.
4. Your tree. Highlight new information.
5. Conclusions. What implications do your results have for your study group and evolutionary biology more broadly?

Tips: https://research.usu.edu/undergradresearch/oral-presentations/

Great example: https://www.youtube.com/watch?v=fZ0NzM6g7jk

## Writing a paper

Start by reading [this chapter](https://bookdown.org/pkaldunn/Book/WritingResearch.html).

Your presentation forms a great outline for your final paper.
Start by writing down everything you said for your presentation. Try noting different subsections.
You might have to read more to completely elaborate on what you want to communicate.
A professional scientific paper is approximately 4000-8000 words.
However, your work, being focused on the phylogeny and perhaps not including any further discussion of evolution, is likely appropriate for a note in the jounal [Molecular Phylogenetics and Evolution](https://www.journals.elsevier.com/molecular-phylogenetics-and-evolution). Read their [publishing guide](https://www.elsevier.com/journals/molecular-phylogenetics-and-evolution/1055-7903/guide-for-authors).

Example paper: https://www.scopus.com/record/display.uri?eid=2-s2.0-85030790294&origin=inward&txGid=b595bcdd0a2d7c7bb08bb94ba060397f

https://writing-speech.dartmouth.edu/learning/materials/sources-and-citations-dartmouth

### Methods

Start by writing down your methods. You know what you did so this is usually the best place to start.

Watch the following for ideas:
https://www.youtube.com/watch?v=JzWUmkxlbEw

### Results

Next, write your results.
Start by putting your phylogeny in your paper.
Based on your presentation you should know what you observe here.

### Intro

Move on to your Introduction.
Before you write anything new, go back to what you wrote at the beginning of this course.
What information is important about your group?
What were your initial hypotheses about relationships?
What conflicts in prior results were you interested in?
Were their traits whose evolutionary process was in question?

### Discussion

Finally, wrap up the paper.
What conclusions have you made that you want to share with readers?
You should recap some of the same questions that came up in your introduction.
Do you have answers now?

### Bibliography

You'll need to keep track of everything you are reading. Follow [these instructions](https://uri.libguides.com/zotero/home) to download and install Zotero. This software will allow you to automatically collect information about the papers you are reading and allow you to easily insert references in your paper using the Google Doc extension.
