# Appendix {-}

## Research Ideas {-}

Feeling a little lost as to how to pick a group to work on?
There are so many species out there.  It is hard to know what might be interesting.
To get you started here are some examples of past research questions:

* Did disease-carrying ticks evolve so that closely related species carry the same parasite? Or do distantly related species have a single species of parasite that they carry?
* Did birds evolve to live on water once or more times?
* Do plants in South America that look similar share a common ancestor, or did that phenotype evolve more than once to adapt to the environment?

Here are some groups that are studied at URI that you might find interesting:

* Hard coral (Scleractinia). Consider how *Astrangia poculata* might have evolved to live in the cold waters of New England (in doing background research look up the whole family).

* Adelgids. How did these species (hemipteran parasites on trees such as hemlock) parasitize species of trees?

* Sharks
